### PR TITLE
fix(edit): construct correct abspath to skel directory

### LINKED ISSUE #57: Edit breaks outside of project root
If you run `helm edit` outside of the project root, it fails with a file open error .. likely due to the `skel` directory lookup.

### PR DESCRIPTION
**Pull request by gabrtv**
fixes #57

### CODE REVIEW

**Comment by adamreese** [comment]
This opens up a blank file in my editor

**Comment by adamreese** [comment]
also running without args gives
```
% ./helm.bin edit                                                                                                                                               [f8f8d96] ruby-2.2.3
panic: runtime error: index out of range

goroutine 1 [running]:
main.edit(0xc8201ac900)
	/Users/adamreese/p/go/src/github.com/deis/helm/helm/helm.go:191 +0xea
github.com/deis/helm/vendor/github.com/codegangsta/cli.Command.Run(0x6d5bc8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x783060, 0x29, 0x0, ...)
	/Users/adamreese/p/go/src/github.com/deis/helm/vendor/github.com/codegangsta/cli/command.go:131 +0x1055
github.com/deis/helm/vendor/github.com/codegangsta/cli.(*App).Run(0xc8201ac6c0, 0xc82000a380, 0x2, 0x2, 0x0, 0x0)
	/Users/adamreese/p/go/src/github.com/deis/helm/vendor/github.com/codegangsta/cli/app.go:175 +0xfd6
main.main()
	/Users/adamreese/p/go/src/github.com/deis/helm/helm/helm.go:128 +0xac2

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
github.com/deis/helm/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0xa19900)
	/Users/adamreese/p/go/src/github.com/deis/helm/vendor/github.com/golang/glog/glog.go:879 +0x67
created by github.com/deis/helm/vendor/github.com/golang/glog.init.1
	/Users/adamreese/p/go/src/github.com/deis/helm/vendor/github.com/golang/glog/glog.go:410 +0x297
```

**Comment by gabrtv** [comment]
@adamreese good find! I can reproduce with `mvim` locally. I'll work on a fix before we proceed.

**Comment by gabrtv** [comment]
@adamreese turns out the problem was the `defer os.Remove` which was firing before `MacVim` came up.  Works now on my box.  Please give it another go.

**Comment by adamreese** [comment]
@gabrtv I came to the same conclusion but I could not get it working.  I was trying to pass the `os.File` pointer to see if defer would keep it open.

branch still does not work on my box though...  I will hack on it a bit and make sure it's not some wired rc file setting

**Comment by gabrtv** [comment]
The problem was with editors that fork. The choice was to try and track the child process exit, or just leave the tempfile around and let the OS clean it up.  We went with the latter, as I'm pretty sure that's what Homebrew is doing.

**Pull request merged**
