### PR TITLE
Charts for Standalone Redis and Example Todo App

### PR DESCRIPTION
**Pull request by gabrtv**
These charts work together to provide a working Todo App that uses Helm-conventions to facilitate Kubernetes-native service discovery via environment variables.  Note the example app is currently bound to the cluster `NodePort` of `30000`.

### CODE REVIEW

**Comment by technosophos** [comment]
Great working example of the self-wiring services/rc model.

**Comment by sgoings** [comment]
Can this wait to be merged until I can have Travis CI verify that it's working on a kube cluster?

**Comment by gabrtv** [comment]
@sgoings yes I'll hold it.  Let me know when the tests are wired up. If anything breaks I'm sure it's your fault. :stuck_out_tongue:

**Comment by gabrtv** [comment]
Closing in favor of merging these into deis/charts repo.

**Comment by bacongobbler** [comment]
Looks like I'll have to do the same. I have a Riak chart available when that repo is up.

**Pull request closed without merging**
