### PR TITLE
chore(*) rename test/ to  _test/

### PR DESCRIPTION
**Pull request by michelleN**
This resolves issue #92.

### CODE REVIEW

**Comment by technosophos** [comment]
This looks good to me. IIRC, @bacongobbler had a reason to not rename `docs` to `_docs`, but when I read back through the issue, I couldn't find it.

**Comment by michelleN** [comment]
@technosophos could be for mkdocs reasons? @bacongobbler

**Comment by bacongobbler** [comment]
yup. I don't think we'll ever be writing .go files in docs/ so I didn't think it made sense to add an underscore to that dir.

**Comment by michelleN** [comment]
okay cool I'll take that out.

**Comment by michelleN** [comment]
ready for review @technosophos @bacongobbler

**Pull request merged**
