### PR TITLE
fix(*): add no-version-check flag to update

### PR DESCRIPTION
**Pull request by technosophos**
Addresses #174

### CODE REVIEW

**Comment by adamreese** [comment]
```
% make test                                                                                                                                                  
go test -v ./. ./manifest ./action ./log ./chart ./dependency ./release
../../google/go-github/github/github.go:22:2: cannot find package "github.com/google/go-querystring/query" in any of:
	/usr/local/Cellar/go/1.5.1/libexec/src/github.com/google/go-querystring/query (from $GOROOT)
	/Users/adamreese/p/go/src/github.com/google/go-querystring/query (from $GOPATH)
make: *** [test] Error 1

% make bootstrap                                                                                                                                             [f77750f] ?? ruby-2.2.3
glide -y glide-full.yaml up
Oops! interface conversion: yaml.Node is yaml.Map, not yaml.List
make: *** [bootstrap] Error 1
```

**Comment by technosophos** [comment]
Upgrade Glide to 0.7

**Comment by adamreese** [comment]
rad

**Comment by bacongobbler** [comment]
my only concern is that we're relying on github to ensure that the v3 API never changes, but they've been great with that so I'm okay with mocking out their API.

**Pull request merged**
