### PR TITLE
feat(README): adjust installing/using/building helm

### LINKED ISSUE #95: README should not suggest `go get`
The README currently suggests the user `go get ...` the project. But because `go get` is not version-aware, Kubernetes will always break (it has hard dependencies), and so it is basically impossible for `helm` to build.

We should suggest a binary release and add instructions for a build via `make`.

### PR DESCRIPTION
**Pull request by sgoings**
Fixes #95

### CODE REVIEW

**Comment by michelleN** [comment]
@sgoings How come we're not suggesting to clone the repository and run the make commands?

**Comment by bacongobbler** [comment]
@michelleN read a little lower down the README changes. they're there! :)

**Comment by michelleN** [comment]
Gotchya thanks @bacongobbler

**Comment by michelleN** [comment]
@sgoings On line 80, should it be cd $GOPATH/github.com/deis/helm instead of $GOPATH/github/deis/helm?

**Comment by sgoings** [comment]
@michelleN fixed. Good eye.

**Comment by michelleN** [comment]
Thanks. This looks good to me. The prebuilt binaries are not available just yet (in the bintray links) but the directions look great.

**Comment by sgoings** [comment]
They are... just not in the release bintray link. The CI build pipeline link takes you to the helm-ci repo which has artifacts. See: https://bintray.com/deis/helm-ci/helm/view

**Pull request merged**
