### PR TITLE
Readme update with bintray URLs pointing to .../view#files

### PR DESCRIPTION
**Pull request by rimusz**

### CODE REVIEW

**Comment by sgoings** [comment]
I'm not sure this behavior gives us what we want... This will send people to the list of all of the versions we have produced. What about just adding #files after _latestVersion... Will that work?

**Comment by rimusz** [comment]
@sgoings that way works too, shall I rebase my PR?

**Comment by bacongobbler** [comment]
If you can modify your commit messages such that they follow the style guidelines, that would be perfect :)

**Comment by rimusz** [comment]
closing in favour of #203

**Pull request closed without merging**
