### PR TITLE
feat(*): show information when an updated Helm version is available

### PR DESCRIPTION
**Pull request by technosophos**
When a newer release is indicated on the Release page of GitHub, this will display version information.

It works by comparing the remote version with the local version, and suggesting an update. This is totally SemVer 2.0 based.

Addresses #136

### CODE REVIEW

**Comment by adamreese** [comment]
We should add a test for this soon...

**Comment by technosophos** [comment]
I guess we could mock the GitHub library and simulate some versions. That actually wouldn't be too hard.

**Comment by bacongobbler** [comment]
We could also do a standalone test where we compile helm with version = latest - 1. That way we're not relying on mocks, but that means we rely on github uptime.

**Comment by carmstrong** [comment]
:+1: For testing the function

**Comment by bacongobbler** [comment]
LGTM (on mobile). Nice test.

**Comment by carmstrong** [comment]
:ship:

**Pull request merged**
